import type { TutorialSourceChapter } from "./tutorial-targets";

export const salesTutorialChapters = [
  {
    id: 1,
    module: "M1 · DA CHEGADA AO FECHAMENTO",
    title: "Bem-vinda ao CoteCerto",
    hook: '"Tá... primeiro dia. Por onde começo?"',
    duration: "~4 min",
    steps: [
      {
        page: "home",
        target: null,
        pos: "center",
        hook: '"Oi! Eu sou a Rafinha — corretora aqui na Supper há um tempinho. Vou te acompanhar nessa primeira semana."',
        title: "Bem-vinda à Supper",
        body: "<p>O CoteCerto é o sistema que você vai usar todo dia pra atender cliente, gerar cotação, fechar venda e cuidar do pós. Tudo num lugar só.</p><p>Nesse primeiro capítulo, eu te mostro <strong>onde fica cada coisa</strong>. Sem pressa — depois você revisita quando quiser.</p>",
        tip: {
          label: "Antes de começar",
          text: 'Você pode pausar o tutorial a qualquer momento clicando em "Sair". Volte pelo botão Tutorial no topo da tela.',
        },
      },
      {
        page: "home",
        target: ".sidebar",
        pos: "right",
        title: "Essa é a sua navegação",
        body: "<p>Tudo no CoteCerto fica no menu da esquerda, seguindo o ciclo da venda: <strong>Início</strong>, <strong>Atender agora</strong>, <strong>Pipeline</strong>, <strong>Novo lead</strong>, <strong>Cotações</strong>, <strong>Propostas</strong>, <strong>Aceite & transmissão</strong>, <strong>Extrato</strong> e <strong>Mensagens prontas</strong>.</p><p>O número amarelo mostra o que precisa da sua atenção em cada área. No Pipeline tem <strong>17</strong> leads ativos hoje.</p>",
      },
      {
        page: "home",
        target: '.nav-item[data-nav="atender"]',
        pos: "right",
        title: "Atender agora — sua fila mais quente",
        body: "<p>Quando a matriz te distribui um lead de campanha, ele cai aqui — e <strong>o relógio começa a correr</strong>. Você tem 3 minutos pra reagir, senão o lead volta pra fila e vai pra outro vendedor.</p><p>O contador também aparece numa <strong>pílula vermelha no topo</strong>, visível em qualquer tela. Lead de campanha é cliente com a aba aberta agora: quem liga primeiro, fecha.</p>",
        tip: {
          label: "Por que tão rápido?",
          text: "Responder em minutos (não horas) multiplica a chance de conversão. Por isso a urgência — e o sistema te avisa em qualquer tela.",
        },
      },
      {
        page: "atender",
        target: "#page-atender .atender-grid",
        pos: "top",
        title: 'Sua fila de "Atender agora"',
        body: '<p>Esta é a tela: cada card é um lead distribuído pela matriz, com o <strong>cronômetro</strong> correndo. Clique em <strong>"Assumir e iniciar"</strong> para atender antes que o lead volte pra fila, ou em <strong>"Ver lead"</strong> para os detalhes.</p>',
        tip: {
          label: "O atalho do topo",
          text: 'O botão vermelho "Atender agora" no topo te traz pra cá de qualquer tela, sempre mostrando quantos leads estão esperando.',
        },
      },
      {
        page: "home",
        target: ".topbar .search",
        pos: "bottom",
        title: "Encontre tudo aqui",
        body: "<p>Quando você já tem cliente cadastrado, a busca é o caminho mais rápido. Procure por <strong>nome, placa do veículo ou número da cotação</strong>.</p>",
        tip: {
          label: "Atalho",
          text: 'Pressione "/" em qualquer tela pra cair direto na busca.',
        },
      },
      {
        page: "home",
        target: "#btnNovoLead",
        pos: "bottom",
        title: "Lead novo? Comece por aqui",
        body: "<p>Esse botão amarelo abre direto a aba <strong>Novo lead</strong> com o formulário em branco — pra você cadastrar quem veio por fora da matriz (indicação, WhatsApp direto, evento). Leads que caem da matriz aparecem sozinhos no Pipeline na coluna Novo.</p>",
      },
      {
        page: "home",
        target: "#sideUser",
        pos: "right",
        title: "É você, na base do menu",
        body: "<p>No rodapé do menu ficam o seu <strong>perfil</strong> e o <strong>sininho de notificações</strong>. Por aqui você acessa seus dados e desloga. Deixei a barra de cima mais limpa, com só o essencial.</p>",
      },
      {
        page: "home",
        target: ".hero-placar",
        pos: "bottom",
        title: "Seu placar do mês",
        body: "<p>A primeira coisa que você vê é como seu mês está indo: <strong>quantas apólices fechou</strong>, se está <strong>no ritmo</strong> da meta, e — o que mais importa — <strong>quanto de comissão ainda está na mesa</strong> pra você buscar.</p><p>Meta deixa de ser cobrança e vira placar de jogo. Atualiza sozinho, em tempo real.</p>",
        tip: {
          label: "Dica de quem já viveu",
          text: 'Olhe o "ritmo necessário". Se precisa de 1 apólice a cada 2 dias e está atrás, priorize os leads mais quentes hoje mesmo.',
        },
      },
      {
        page: "home",
        target: ".mission-row",
        pos: "right",
        title: "Sua missão de hoje",
        body: "<p>Meta do mês assusta. Por isso o sistema quebra ela em <strong>tarefas pequenas e batíveis do dia</strong>: tantos contatos, tantas cotações, tantas propostas.</p><p>Vá marcando conforme avança. Bater a missão todo dia é o hábito que fecha a meta no fim do mês — e mantém sua sequência. 🔥</p>",
      },
      {
        page: "home",
        target: "#meuFunilCard",
        pos: "top",
        title: "Meu funil — onde você perde",
        body: '<p>Seu funil do lead ao fechamento, com a <strong>conversão de cada etapa</strong>. O degrau em vermelho é o seu ponto mais fraco — e vem com uma <strong>dica de coaching</strong> específica pra melhorar ali.</p><p>Em vez de "melhore sua conversão", o sistema te diz exatamente <strong>onde</strong> e <strong>como</strong>.</p>',
      },
      {
        page: "home",
        target: ".actions-list",
        pos: "right",
        title: "O que fazer agora — com retorno",
        body: "<p>O sistema empurra o que precisa de ação: <strong>cotações que vão expirar, propostas sem resposta e leads parados</strong>. E ao lado de cada uma, <strong>quanto vale em comissão</strong> — pra você priorizar pelo retorno.</p><p>É clicável: cada item leva direto pra área certa.</p>",
      },
      {
        page: "home",
        target: ".pos-row",
        pos: "left",
        title: "Sua posição na equipe",
        body: "<p>Aqui você se compara com o time — <strong>sua posição</strong> e a sua conversão <strong>vs. a média da equipe</strong>. E logo abaixo, suas <strong>conquistas</strong> (primeira venda, sequências, metas).</p><p>A ideia não é pressão: é mostrar onde dá pra crescer e comemorar cada avanço.</p>",
      },
      {
        page: "home",
        target: "#trendChart",
        pos: "top",
        title: "Sua semana num olhar",
        body: "<p>Os últimos 7 dias: quantos <strong>leads</strong> chegaram, quantas <strong>cotações</strong> você gerou, quantos <strong>fechamentos</strong> aconteceram. Útil pra perceber se uma campanha virou tráfego ou se tem dia da semana melhor.</p>",
      },
    ],
    outro: {
      hook: '"Entendeu o lay-out? Bora ver onde os leads moram."',
    },
  },
  {
    id: 2,
    module: "M1 · DA CHEGADA AO FECHAMENTO",
    title: "Seu pipeline em um olhar",
    hook: '"Esse é o lugar onde você passa mais tempo. Vou te mostrar como ele funciona."',
    duration: "~4 min",
    steps: [
      {
        page: "pipeline",
        target: null,
        pos: "center",
        title: "Bem-vinda ao Pipeline",
        body: "<p>O pipeline é o seu mapa de quem está em cada momento da venda. Cada coluna é um estágio; cada cartãozinho é um lead. Da esquerda pra direita, é o caminho que o cliente percorre da chegada ao fechamento.</p>",
        tip: {
          label: "Por que kanban?",
          text: 'Você bate o olho e sabe onde tem gargalo. Se a coluna "Cotando" estiver entupida e "Proposta enviada" vazia, é sinal de que tem cotação encalhando.',
        },
      },
      {
        page: "pipeline",
        target: '.kcol[data-stage="Novo"]',
        pos: "right",
        title: 'Tudo começa em "Novo"',
        body: '<p>Lead que chegou e ninguém ainda contactou. Sua missão aqui é simples: <strong>ligar, qualificar e mover pra "Qualificando".</strong></p><p>Repare no <strong>contador no topo de cada cartão</strong>: você tem <strong>3 minutos</strong> pra reagir a partir da distribuição da matriz. Se não tratar, o lead volta pra fila e vai pra outro vendedor. Verde = ainda dá tempo, amarelo = atenção, vermelho = correr.</p>',
        tip: {
          label: "Por que tão apertado?",
          text: "Cliente que pediu cotação agora está com a aba aberta. Quanto mais cedo você ligar, mais quente ele está — e maior a chance de fechar.",
        },
      },
      {
        page: "pipeline",
        target: ".filters-bar",
        pos: "bottom",
        title: "Filtros pra focar",
        body: "<p>Quando o pipeline tem 50, 80 leads, os filtros salvam sua vida. Pode filtrar por <strong>origem</strong> (orgânico, indicação, campanha), por <strong>seguradora</strong> ou por <strong>período</strong>.</p>",
      },
      {
        page: "pipeline",
        target: ".kcard",
        pos: "right",
        title: "Anatomia de um lead",
        body: '<p>Cada cartão te diz, em 2 segundos: o <strong>nome do cliente</strong>, o <strong>veículo</strong>, o <strong>valor estimado da apólice por ano</strong>, há quantos <strong>dias</strong> está nesse estágio (fica vermelho se passar de 7), e qual é a <strong>próxima ação sugerida</strong> — a faixinha amarela embaixo.</p><p>Em alguns cartões aparecem chips extras no topo: <strong>contador da matriz</strong> (em Novo) ou <strong>"Aguardando seguradora"</strong> (em Em negociação, quando a proposta já foi transmitida e tá só esperando a seguradora responder).</p>',
        tip: {
          label: "Dica",
          text: "Confie na próxima ação sugerida. Ela considera o estágio, o tempo e o histórico — quase sempre é o melhor próximo passo.",
        },
      },
      {
        page: "pipeline",
        target: ".page-head .toggle",
        pos: "bottom",
        title: "Kanban OU tabela",
        body: "<p>Se você prefere ver tudo em lista (com colunas ordenáveis e mais informação por linha), troca aqui. Mesma data, visão diferente.</p>",
      },
      {
        page: "pipeline",
        target: ".kanban",
        pos: "top",
        title: "Mover é arrastar",
        body: "<p>Você pode <strong>arrastar um cartão</strong> de uma coluna pra outra. O sistema atualiza o estágio sozinho e zera o contador de dias. Tente arrastar o João Silva da coluna Novo para Qualificando — só pra sentir.</p>",
      },
      {
        page: "pipeline",
        target: ".kcard",
        pos: "right",
        title: "Pra abrir um lead",
        body: "<p>Clique no cartão. No próximo capítulo, a gente vai entrar no João Silva — você vai conhecer o cliente do zero e gerar a primeira cotação dele.</p>",
      },
    ],
    outro: {
      hook: '"Pega um café. O próximo capítulo é o coração do sistema."',
    },
  },
  {
    id: 3,
    module: "M1 · DA CHEGADA AO FECHAMENTO",
    title: "Conhecendo o João",
    hook: '"Lead aberto. Agora vem a parte que dá medo no começo — mas tem menos campo do que parece."',
    duration: "~6 min",
    steps: [
      {
        page: "lead",
        target: null,
        pos: "center",
        title: "Você entrou no João Silva",
        body: "<p>Essa tela é onde você faz três coisas ao mesmo tempo: <strong>qualifica o cliente</strong> (entende quem é), <strong>monta a cotação</strong> (que coberturas faz sentido) e já <strong>prepara a emissão</strong>.</p><p>Vou te mostrar passo a passo. Não se assuste com a quantidade de campos — o sistema preenche a maior parte sozinho.</p>",
        prepare: "lead-step-0",
      },
      {
        page: "lead",
        target: "#stepperBar",
        pos: "bottom",
        title: "Seis passos, espelhando o Quiver",
        body: '<p>A cotação tem <strong>6 passos</strong>: <strong>Segurado → Seguro → Veículo → Perfil → Coberturas → Cálculo</strong>. É o mesmo caminho do Quiver, com a cara da Supper — a curva de aprendizado é baixa.</p><p>Você avança e volta à vontade. Quando o mínimo está preenchido, o selo verde <strong>"Pronto para cotar"</strong> aparece aqui.</p>',
      },
      {
        page: "lead",
        target: "#fldCpf",
        pos: "right",
        title: "Passo 1 — Segurado: CPF primeiro",
        body: "<p>Comece pelo CPF. Se o cliente já existir na base, o sistema preenche <strong>nome, data de nascimento, sexo e contatos</strong> sozinho. Se for novo, você digita à mão depois.</p>",
        tip: {
          label: "Experimente",
          text: 'Apague o CPF, cole "247.193.802-09" e clique fora do campo. Vai ver o spinner e o cadastro aparecendo.',
        },
      },
      {
        page: "lead",
        target: "#fldCep",
        pos: "right",
        title: "CEP puxa endereço",
        body: "<p>Mesma lógica: digite o CEP, o sistema busca a rua, bairro, cidade e UF. Você só confirma e segue.</p>",
      },
      {
        page: "lead",
        target: ".wizard-card .wizard-grid",
        pos: "top",
        title: "Passo 2 — Seguro",
        body: "<p>Aqui você marca as <strong>seguradoras</strong> que entram no cálculo, e define <strong>tipo de seguro</strong> (novo ou renovação), <strong>vigência</strong> e <strong>grupo de produção</strong>.</p><p>Se for <strong>renovação</strong>, abre um bloco extra com os dados da apólice anterior e os bônus por seguradora.</p>",
        prepare: "lead-step-1",
      },
      {
        page: "lead",
        target: "#fldPlaca",
        pos: "right",
        title: "Passo 3 — Veículo: placa → FIPE",
        body: "<p>O pulo do gato: <strong>digite só a placa</strong>. O sistema consulta a FIPE e preenche marca, modelo, ano e combustível. Você confere e segue.</p>",
        tip: {
          label: "Sem placa?",
          text: "Em zero km ainda não tem placa. Use a busca por descrição ou código FIPE no mesmo campo.",
        },
        prepare: "lead-step-2",
      },
      {
        page: "lead",
        target: "#foldComp",
        pos: "top",
        title: "Dados complementares — abre só se precisar",
        body: "<p>Caixa fechada por padrão: <strong>chassi remarcado, financiado, antifurto, histórico de leilão, PcD e isenção de imposto</strong>. São perguntas de baixa demanda — ficam recolhidas pra não poluir a cotação.</p><p>Espelha o Quiver, mas sem assustar o cliente na primeira conversa: abre só quando o caso pede.</p>",
      },
      {
        page: "lead",
        target: "#foldVeic",
        pos: "top",
        title: "Blindagem, kit gás e acessórios",
        body: "<p>Outra caixa fechada. Abre só se o veículo tem blindagem, kit gás ou acessórios que impactam o preço — aí o sistema pede a cobertura e o valor de cada item.</p>",
      },
      {
        page: "lead",
        target: ".wizard-card .wizard-grid",
        pos: "top",
        title: "Passo 4 — Perfil: quem dirige",
        body: "<p>Garagem, <strong>proprietário</strong> do veículo, <strong>principal condutor</strong> e se há <strong>jovens de 17 a 25 anos</strong> em casa. Tudo influencia o preço.</p><p>Quando o segurado não é o proprietário ou o condutor, o sistema abre os campos completos da outra pessoa.</p>",
        prepare: "lead-step-3",
      },
      {
        page: "lead",
        target: ".wizard-card .wizard-grid",
        pos: "top",
        title: "Passo 5 — Coberturas: o sistema já sugere",
        body: "<p>Já vem com um <strong>plano pré-selecionado (Fácil)</strong>, modalidade Valor de Mercado e os limites preenchidos (danos a terceiros, APP e danos morais) — um ponto de partida.</p><p>É só o começo: você ajusta tudo no passo seguinte, o <strong>Cálculo</strong>, em frente às seguradoras.</p>",
        prepare: "lead-step-4",
      },
      {
        page: "lead",
        target: "#advCotacao",
        pos: "top",
        title: "Pacote, descontos, comissões e condições especiais",
        body: "<p>Ainda nas Coberturas, você fecha os detalhes que mudam o preço e o seu ganho:</p><p><strong>Mais Assistências</strong> — contrata o pacote ampliado e escolhe a seguradora. <strong>Descontos e agravos</strong> — ajusta, por seguradora, descontos, agravos e regras específicas. <strong>Comissões</strong> — define o % de comissão por seguradora. <strong>Condições especiais</strong> — Worksite, Affinity e grupo segurado, numa visão única.</p><p>Precisa de um desconto além do que você pode dar? Use <strong>Solicitar desconto adicional</strong>: o pedido vai ao seu <strong>superior imediato</strong> e, se passar da alçada dele, sobe na hierarquia até a Matriz. Você pode enviar mais de um pedido na mesma cotação.</p>",
        tip: {
          label: "Por que é fundamental",
          text: "É aqui que você compara o seu ganho entre seguradoras e aplica convênios e condições a que o cliente tem direito — tudo sem sair pra outro sistema.",
        },
        prepare: "lead-step-4",
      },
      {
        page: "lead",
        target: "#resumoCard",
        pos: "left",
        title: "Resumo do lado, sempre",
        body: "<p>Esse painel à direita vai te acompanhar por todos os passos. Conforme você preenche, ele se atualiza.</p><p><strong>Clique em qualquer valor pra editar inline</strong> — não precisa ir buscar o campo lá na frente.</p>",
        tip: {
          label: "Por que isso é importante",
          text: "No sistema antigo (Quiver) você precisava clicar num ícone de lápis pra editar cada coisa. Aqui é só clicar no valor. Parece pequeno, mas economiza minutos por cotação.",
        },
      },
      {
        page: "lead",
        target: ".stepper .ready",
        pos: "bottom",
        title: "Pronto para cotar",
        body: '<p>Esse selo verde aparecendo quer dizer que tem dados suficientes pra rodar o multi-cálculo. Você pode disparar pelo botão amarelo "Calcular cotação" no rodapé do resumo (ou aqui embaixo no wizard).</p>',
        prepare: "lead-ready",
      },
      {
        page: "lead",
        target: "#btnHistorico",
        pos: "bottom",
        title: "Agende um retorno — e seja lembrada",
        body: '<p>Cliente pediu pra ligar amanhã? Falta a foto da CNH? Abra o <strong>Histórico</strong> e use <strong>Agendar retorno</strong>: escolha data, hora e escreva a nota (ex.: "Ligar para cobrar a foto da carteira").</p><p>O sistema te lembra em três lugares: no <strong>"O que fazer agora"</strong> da sua tela inicial, num <strong>aviso no card do lead</strong> no Pipeline e no <strong>sininho</strong>. Nada de anotar em papel ou confiar na memória.</p>',
        tip: {
          label: "Hábito que fecha venda",
          text: "Lead que recebe retorno no horário combinado converte muito mais. Agende sempre o próximo passo antes de sair da cotação.",
        },
      },
      {
        page: "lead",
        target: "#btnClassificarPerda",
        pos: "bottom",
        title: "Não fechou? Classifique a perda",
        body: '<p>Se o cliente não fechar, não deixe o lead largado: clique em <strong>Classificar perda</strong>. Você escolhe o <strong>motivo</strong> e o <strong>sub-motivo</strong> (ex.: "Concorrência → fechou com outro corretor") e devolve o lead pra matriz.</p><p>Você só diz <strong>por que</strong> perdeu. Quem decide se o lead volta pra fila (remalho) ou é descartado é a central de distribuição.</p>',
        tip: {
          label: "Por que isso importa",
          text: "Cada perda classificada vira informação pra matriz reaproveitar o lead e ajustar a distribuição. Lead devolvido sem motivo é oportunidade que some.",
        },
      },
    ],
    outro: {
      hook: '"Botão apertado. Em ~1 segundo, 9 seguradoras te respondem."',
    },
  },
  {
    id: 4,
    module: "M1 · DA CHEGADA AO FECHAMENTO",
    title: "9 seguradoras de uma vez",
    hook: '"Aqui é onde você decide o que recomendar pro cliente."',
    duration: "~4 min",
    steps: [
      {
        page: "compare",
        target: null,
        pos: "center",
        title: "O comparativo multi-seguradora",
        body: '<p>A cotação rodou. As 9 seguradoras que aceitam esse perfil te responderam. Por padrão, o sistema mostra as <strong>top 3</strong> pré-selecionadas por melhor relação preço/cobertura — pra você não se afogar em 9 colunas.</p><p>Antes da gente entrar, repare: <strong>essa aba "Cotações" abre como uma lista</strong>. Você escolhe qual cotação trabalhar e entra no comparativo. Eu já te trouxe pra dentro da cotação do João Silva.</p>',
      },
      {
        page: "compare",
        target: ".compare-table thead",
        pos: "bottom",
        title: "Os selos no topo",
        body: '<p>Cada seguradora vem com um selo que ajuda a contar a história pro cliente:</p><p><strong>Menor preço</strong> (verde) · <strong>Melhor cobertura</strong> (azul) · <strong>Mais escolhido</strong> por clientes parecidos (creme).</p><p>Útil quando o cliente pergunta "por que essa e não aquela?"</p>',
      },
      {
        page: "compare",
        target: ".ctable tbody tr:nth-child(2)",
        pos: "right",
        title: "Coberturas, linha por linha",
        body: "<p>Cada linha é uma cobertura. Você vê o LMI (limite máximo de indenização) e a franquia de cada uma, lado a lado entre as seguradoras.</p>",
        tip: {
          label: "Editável inline",
          text: "Clique em qualquer valor (LMI ou franquia) pra ajustar. Útil quando o cliente quer testar um cenário — ex: aumentar RCF pra 200 mil em todas e ver o impacto.",
        },
      },
      {
        page: "compare",
        target: ".compare-bar .switch",
        pos: "bottom",
        title: "Aplicar em todas ou só em uma",
        body: "<p>Esse interruptor decide se uma alteração de cobertura vale pra <strong>todas as seguradoras</strong> (rápido, pra comparação justa) ou só para <strong>aquela coluna</strong> (mais cirúrgico, pra montar uma proposta diferente).</p>",
      },
      {
        page: "compare",
        target: ".ctable .total-row",
        pos: "top",
        title: "O preço final, com parcelamento",
        body: "<p>A linha amarela traz o <strong>prêmio total</strong> e a forma de parcelamento de cada seguradora. É o número que o cliente quer saber.</p>",
      },
      {
        page: "compare",
        target: "#btnCompareMais",
        pos: "bottom",
        title: "Mais seguradoras?",
        body: '<p>Se quiser forçar a comparação com seguradoras que ficaram de fora (por perfil ou regra), clique em <strong>"Comparar com mais seguradoras"</strong>. Abre a lista completa de seguradoras disponíveis pra você escolher.</p>',
      },
      {
        page: "compare",
        target: ".ctable .actions-row .ins-actions",
        pos: "top",
        title: "Pra cada seguradora, 3 ações",
        body: "<p>No rodapé de cada coluna: <strong>Gerar proposta</strong> (vai pra próxima etapa), <strong>Enviar</strong> (manda por e-mail+WhatsApp esse comparativo) ou <strong>Imprimir</strong>.</p><p>O cliente decidiu pela Azul. Bora gerar a proposta.</p>",
      },
    ],
    outro: {
      hook: '"Comparativo na mão, decisão tomada. Agora a proposta."',
    },
  },
  {
    id: 5,
    module: "M1 · DA CHEGADA AO FECHAMENTO",
    title: "Quando o cliente pede ajuste",
    hook: '"Raramente o cliente aceita a V1. Aqui você negocia sem perder histórico."',
    duration: "~4 min",
    steps: [
      {
        page: "proposal",
        target: null,
        pos: "center",
        title: "A proposta da Azul",
        body: "<p>A aba <strong>Propostas</strong> abre como uma lista de todas as propostas em andamento. Você escolhe qual quer trabalhar e entra no detalhe — eu já te trouxe pra dentro da proposta da Fernanda Souza pra V3.</p><p>Aqui você faz o <strong>ajuste fino</strong> (franquia, cobertura, assistência), define <strong>pagamento e parcelamento</strong>, escreve uma <strong>nota interna</strong> e envia ao cliente.</p>",
      },
      {
        page: "proposal",
        target: ".prop-section:nth-child(2)",
        pos: "right",
        title: "Ajuste fino de cobertura",
        body: "<p>Aqui você muda detalhes que não cabia ajustar no comparativo: forma da franquia, tamanho do RCF, dias de carro reserva, tipo de assistência. Use quando o cliente pede algo específico.</p>",
        prepare: "proposta-ajuste",
      },
      {
        page: "proposal",
        target: ".payment-grid",
        pos: "top",
        title: "Como o cliente vai pagar",
        body: "<p>Três opções: <strong>cartão de crédito</strong> (até 12x sem juros), <strong>boleto</strong> (mensal), <strong>débito automático</strong>. A maioria escolhe cartão.</p>",
      },
      {
        page: "proposal",
        target: ".prop-section:nth-child(5)",
        pos: "right",
        title: "Notas internas (não vão ao cliente)",
        body: '<p>Sempre que mudar algo, escreva aqui <strong>por que mudou</strong>. Ex: "cliente pediu reduzir franquia para R$ 3.000". É só pra você e seu líder verem depois.</p>',
        tip: {
          label: "Por que vale a pena",
          text: 'Quando o cliente volta dois meses depois pedindo "lembra daquela proposta?", a nota é o que te lembra do contexto. Vira diferencial de relacionamento.',
        },
      },
      {
        page: "proposal",
        target: ".history",
        pos: "left",
        title: "Histórico de versões com diff",
        body: '<p>À direita: <strong>cada vez que você envia uma nova versão da proposta</strong>, ela vira uma entrada aqui. Você vê o que mudou de uma versão pra outra (<strong>diff</strong>) e a nota que você escreveu.</p><p>Útil pra cliente que pede "manda de novo aquele cenário com franquia maior" — você acha na hora.</p>',
      },
      {
        page: "proposal",
        target: ".prop-card .row:last-child .btn-yellow",
        pos: "top",
        title: "Enviar nova versão",
        body: "<p>Botão amarelo: gera a próxima versão da proposta e <strong>dispara o e-mail + WhatsApp pro cliente</strong> automaticamente. Você não precisa abrir outro app.</p>",
        prepare: "proposta-envio",
      },
    ],
    outro: {
      hook: '"V3 enviada. Agora a gente espera o cliente clicar Aceito."',
    },
  },
  {
    id: 6,
    module: "M1 · DA CHEGADA AO FECHAMENTO",
    title: "Hora de fechar",
    hook: '"Cliente aceitou. Agora é checar tudo e transmitir."',
    duration: "~3 min",
    steps: [
      {
        page: "aceite",
        target: null,
        pos: "center",
        title: "Aceite & Transmissão",
        body: "<p>A aba <strong>Aceite & transmissão</strong> também abre como uma lista — mostra todas as propostas no fluxo final, com o estado atual de cada uma (Enviada, Visualizada, Aceita ou Aguardando seguradora). Eu te trouxe direto pro detalhe da proposta da Fernanda que tem duas partes: <strong>linha do tempo</strong> em cima e <strong>conferência final</strong> embaixo.</p>",
        prepare: "aceite-aceita",
      },
      {
        page: "aceite",
        target: ".timeline",
        pos: "bottom",
        title: "A linha do tempo do aceite",
        body: "<p>Você acompanha em tempo real os 5 passos: <strong>Enviada → Visualizada → Aceita → Transmitida → Apólice emitida</strong>. Cada passo vem com horário. Útil pra saber se o cliente já abriu, se está em cima ou se travou — e depois, se a seguradora já oficializou.</p>",
        prepare: "aceite-aceita",
        tip: {
          label: "Se o cliente travar",
          text: 'Quando fica muito tempo em "Visualizada" sem aceitar, é hora de ligar. Provavelmente tem dúvida não resolvida.',
        },
      },
      {
        page: "aceite",
        target: ".confer-grid",
        pos: "top",
        title: "Conferência final dos dados",
        body: "<p>Antes de transmitir pra seguradora, você confere TUDO uma última vez: <strong>cliente, veículo, coberturas, prêmio, parcelamento</strong>. Se algo estiver errado, é melhor pegar agora.</p>",
        prepare: "aceite-aceita",
      },
      {
        page: "aceite",
        target: ".confer-check",
        pos: "top",
        title: "O checkbox de responsabilidade",
        body: '<p>Marque "Conferi tudo" pra liberar o botão "Transmitir". É a etapa que te força a olhar — porque depois de transmitir, mudar fica complicado.</p>',
        prepare: "aceite-aceita",
      },
      {
        page: "aceite",
        target: "#btnTransmit",
        pos: "top",
        title: "Transmitir = oficializar a venda",
        body: '<p>Esse clique manda os dados pra seguradora montar a apólice oficial. A proposta passa pro estado <strong>"Aguardando seguradora"</strong> e fica visível tanto aqui na lista quanto no card do Pipeline (em "Em negociação"). Quando a seguradora confirma, o lead vai pra coluna <strong>Fechado</strong> do Pipeline e a venda entra no seu <strong>Extrato</strong>.</p>',
        prepare: "aceite-aceita",
      },
      {
        page: "aceite",
        target: ".confer-card",
        pos: "left",
        title: "E se a seguradora pedir uma pendência?",
        body: '<p>Nem sempre a emissão sai direto. Enquanto está <strong>"Aguardando seguradora"</strong>, ela pode devolver uma <strong>pendência</strong> antes de emitir — uma CNH, um comprovante, uma vistoria.</p><p>Ela aparece aqui em destaque vermelho. Você responde no campo, e registra <strong>quem resolveu</strong>: você (vendedor) ou a matriz, nos casos mais complexos. Resolvida, a proposta volta pra reanálise e segue pra emissão.</p>',
        prepare: "aceite-pendencia",
        tip: {
          label: "Não deixe parar",
          text: "Pendência parada trava a venda e some da sua comissão. A matriz também enxerga isso e cobra — mas no seu lado, resolva assim que cair.",
        },
      },
      {
        page: "aceite",
        target: null,
        pos: "center",
        title: "Você fechou sua primeira venda!",
        body: "<p>Sério, parabéns. Da chegada do lead à transmissão, você viveu o ciclo completo.</p><p>Antes de fechar, vou te mostrar uma ferramenta que vai facilitar muito o seu dia a dia com o cliente.</p>",
        prepare: "aceite-aceita",
      },
    ],
    outro: {
      hook: '"Bora ver as mensagens prontas — elas economizam um tempão."',
    },
  },
  {
    id: 7,
    module: "M1 · DA CHEGADA AO FECHAMENTO",
    title: "Mensagens prontas",
    hook: '"Travou no que escrever pro cliente? Isso aqui resolve."',
    duration: "~2 min",
    steps: [
      {
        page: "msgs",
        target: null,
        pos: "center",
        title: "Sua biblioteca de mensagens",
        body: "<p>Principalmente no começo, a gente trava na hora de escrever pro cliente. Aqui estão os <strong>modelos aprovados pela Supper</strong> pra cada momento: primeiro contato, follow-up, cotação enviada, documentos, reativação.</p><p>É só achar, copiar e enviar.</p>",
      },
      {
        page: "msgs",
        target: ".msg-cat-bar",
        pos: "bottom",
        title: "Organizadas por categoria",
        body: "<p>Filtre pela etapa em que o cliente está — ou use a busca. Você acha a mensagem certa em segundos, sem ficar caçando.</p>",
      },
      {
        page: "msgs",
        target: ".msg-card",
        pos: "right",
        title: "Já vêm preenchidas pra você",
        body: '<p>Repare: a mensagem já vem com o <strong>nome do cliente</strong> e os seus dados preenchidos automaticamente — nada de "Olá, [nome]".</p><p>Dois botões: <strong>Copiar</strong> (pra colar onde quiser) e <strong>WhatsApp</strong> (abre a conversa com o texto pronto). No futuro, a integração com o WhatsApp deixa isso ainda mais direto.</p>',
        tip: {
          label: "Padronização",
          text: "As mensagens são oficiais (a matriz cuida disso): você comunica com a cara da Supper e sem prometer cobertura que não existe.",
        },
      },
    ],
    outro: {
      hook: '"Fim do Módulo 1! Última parada: ver o quanto você ganhou."',
      big: true,
    },
  },
  {
    id: 8,
    module: "M2 · O QUE VOCÊ GANHA",
    title: "Sua comissão, em tempo real",
    hook: '"Você vendeu. Agora vamos ver quanto isso vira pra você."',
    duration: "~3 min",
    steps: [
      {
        page: "extrato",
        target: null,
        pos: "center",
        title: "Extrato de vendas",
        body: "<p>Toda apólice que você fecha alimenta esse painel. É <strong>a sua visão pessoal</strong>: quanto vendeu, quanto vai receber, quanto bateu da meta, e como você está em relação à equipe.</p><p>Antes só dava pra ver isso na planilha do líder — agora tem aqui, sempre atualizado.</p>",
      },
      {
        page: "extrato",
        target: "#page-extrato .kpi-grid",
        pos: "bottom",
        title: "Seu mês em 6 números",
        body: "<p>Em duas linhas de três: <strong>quantas vendas, R$ vendido, comissão bruta, estornos, líquido a receber e % da meta</strong>. Tudo do período selecionado no filtro acima — por padrão, o mês corrente.</p>",
        tip: {
          label: "Líquido = bruto − estornos",
          text: 'A comissão "bruta" é o total das vendas. Mas se uma apólice for cancelada nos primeiros dias, ela vira estorno e desconta. O que entra no seu bolso é o líquido.',
        },
      },
      {
        page: "extrato",
        target: "#page-extrato .extrato-filters",
        pos: "bottom",
        title: "Fatie como precisar",
        body: "<p>Defina <strong>De/Até</strong> pra abrir o período que quiser (este mês, último trimestre, ano inteiro, qualquer recorte). Quer ver só vendas pendentes de pagamento? Filtra por status. Só Porto pra checar a campanha? Filtra por seguradora. O total no rodapé e os KPIs no topo respeitam os filtros.</p>",
      },
      {
        page: "extrato",
        target: "#page-extrato .extrato-table-card .table-pipe tbody tr:first-child",
        pos: "top",
        title: "Cada linha é uma venda sua",
        body: "<p>Você vê <strong>data, número da apólice, cliente, seguradora, tipo, valor, %, R$ de comissão e quando o pagamento vai cair</strong>. Pendente significa que a seguradora ainda não repassou — geralmente cai 30-45 dias depois da emissão.</p>",
        prepare: "extrato-venda",
      },
      {
        page: "extrato",
        target: "#page-extrato .extrato-estornos",
        pos: "top",
        title: "Estornos — fique de olho",
        body: "<p>Quando uma apólice cancela cedo (cliente desiste em 7 dias, ou primeira parcela não paga), a comissão é estornada. Esse bloco te mostra o impacto no mês.</p>",
        tip: {
          label: "Reduzir estornos",
          text: "Contato pós-venda nos primeiros 7 dias derruba muito o cancelamento. Se ainda não fez no cliente recém-fechado, vale ligar.",
        },
      },
      {
        page: "extrato",
        target: "#page-extrato .extrato-campanha",
        pos: "top",
        title: "Campanhas ativas",
        body: "<p>A Porto está com bônus de 2% extra pra quem fechar 5 apólices novas no mês. Você já bateu 3 — faltam 2 até 31/05.</p><p>As campanhas aparecem aqui pra não passar batido.</p>",
        prepare: "extrato-campanha",
      },
      {
        page: "extrato",
        target: "#page-extrato .extrato-pagamentos",
        pos: "top",
        title: "Quando o dinheiro entra",
        body: "<p>Cada seguradora tem seu calendário. Esse bloco antecipa <strong>quanto vai cair em cada data</strong> nas próximas semanas. Útil pra planejar seu fluxo de caixa pessoal.</p>",
        prepare: "extrato-pagamentos",
      },
    ],
    outro: {
      hook: '"E é isso — você terminou o tutorial. Não tem mais segredo no CoteCerto pra você."',
      big: true,
      final: true,
    },
  },
] satisfies TutorialSourceChapter[];
