import type { TutorialSourceChapter } from "./tutorial-targets";

export const matrizTutorialChapters = [
  {
    id: 1,
    module: "M1 · COMANDO DA OPERAÇÃO",
    title: "Bem-vinda, Ana",
    hook: '"Assumi a supervisão. Por onde eu começo?"',
    duration: "~3 min",
    steps: [
      {
        page: "mdash",
        target: null,
        pos: "center",
        hook: '"Olá, Ana! Eu sou o assistente do CoteCerto. Vou te mostrar como comandar a operação da Supper daqui."',
        title: "Bem-vinda ao centro de comando",
        body: "<p>Enquanto o vendedor cuida do dia a dia da venda, a sua função é uma camada acima: <strong>distribuir, acompanhar, cobrar, auditar e remunerar</strong>. Tudo que hoje vive espalhado em planilhas, aqui fica num lugar só.</p><p>Vou te apresentar cada área, Ana. Sem pressa.</p>",
        tip: {
          label: "A qualquer momento",
          text: 'Você pausa pelo botão "Sair" e volta pelo Tutorial no topo. Este tour é da área da Matriz.',
        },
      },
      {
        page: "mdash",
        target: ".sidebar",
        pos: "right",
        title: "Seu menu de comando",
        body: "<p>À esquerda ficam as áreas da Matriz, em dois grupos: <strong>COMANDO</strong> (Visão geral, Leads, Distribuição, <strong>Aprovações</strong>) e <strong>OPERAÇÃO</strong> (Franquias, Vendedores, Supervisão, Pipeline geral, Vendas, Comissões, Premiações, Estornos, Renovações, Relatórios, Mensagens, <strong>Acessos e permissões</strong> e Configurações).</p><p>É a operação inteira na ponta dos dedos.</p>",
      },
      {
        page: "mdash",
        target: "#reactPill",
        pos: "bottom",
        title: "O alarme que te segue",
        body: '<p>Essa pílula no topo aparece em <strong>qualquer tela</strong> sempre que houver lead esperando distribuição — com o tempo do mais antigo. É o seu sinal de "age agora": lead de campanha parado é dinheiro esfriando.</p>',
      },
      {
        page: "mdash",
        target: "#sideUser",
        pos: "right",
        title: "É você, Ana",
        body: "<p>Na base do menu ficam o seu perfil e as notificações. Você está logada como <strong>Ana · Supervisora</strong> — e é por isso que eu falo com você pelo nome. 😉</p>",
      },
      {
        page: "maprov",
        target: "#page-maprov .table-pipe",
        pos: "top",
        title: "Aprovações de desconto — última instância",
        body: "<p>Quando um vendedor pede desconto além da política, o pedido <strong>sobe pela hierarquia</strong> (franqueado → master/supervisor) e, no limite, chega <strong>à Matriz</strong>. Aqui você vê só os pedidos endereçados à Matriz, com a <strong>trilha</strong> de quem já concedeu o quê. Dá para <strong>Abrir a cotação</strong> e conferir antes de responder — aprovar, contrapropor ou negar.</p>",
        tip: {
          label: "Respostas-padrão",
          text: 'Na aba "Respostas padrão" você mantém modelos de resposta por seguradora e por vendedor, reaproveitáveis na hora de decidir.',
        },
      },
    ],
    outro: {
      hook: '"Menu na cabeça. Bora ver o painel que resume a operação."',
    },
  },
  {
    id: 2,
    module: "M1 · COMANDO DA OPERAÇÃO",
    title: "O painel da operação",
    hook: '"Cheguei de manhã. O que olho primeiro?"',
    duration: "~4 min",
    steps: [
      {
        page: "mdash",
        target: "#page-mdash .card-yellow",
        pos: "bottom",
        title: "Resumo do dia — sua meta diária",
        body: "<p>Comece o dia por aqui, Ana. Em uma linha: quantas propostas estão <strong>em transmissão</strong>, quantas com <strong>pendência</strong>, quantos leads <strong>sem atendimento</strong>, <strong>SLA estourado</strong> e <strong>fechados hoje</strong>. Cada número é clicável e te leva direto pra ação.</p>",
      },
      {
        page: "mdash",
        target: "#page-mdash .mkpi-grid",
        pos: "top",
        title: "A operação em números",
        body: "<p>O retrato do mês: leads recebidos e distribuídos, sem atendimento, tempo médio de 1º contato, vendas emitidas/pagas/não pagas, conversão geral e comissão gerada. É o que antes vivia em cinco planilhas diferentes.</p>",
      },
      {
        page: "mdash",
        target: "#page-mdash .actions-list",
        pos: "left",
        title: "Alertas críticos do dia",
        body: "<p>O sistema te empurra o que não pode esperar: pendências na transmissão, leads sem atendimento, SLA estourado, franquia abaixo da meta, vendas não pagas. Cada alerta leva direto pra área de agir.</p>",
        tip: {
          label: "Hierarquia de urgência",
          text: "Vermelho é o que perde dinheiro ou lead agora. Amarelo é atenção. Use essa ordem pra priorizar a manhã.",
        },
      },
      {
        page: "mdash",
        target: "#page-mdash .rank-row",
        pos: "left",
        title: "Quem está puxando o resultado",
        body: "<p>Rankings de <strong>franquias</strong> e <strong>vendedores</strong>, clicáveis pra abrir o detalhe de cada um. Bom pra reconhecer quem vai bem e identificar quem precisa de apoio.</p>",
      },
    ],
    outro: {
      hook: '"Esse painel é seu ponto de partida todo dia. Agora, o coração da operação."',
    },
  },
  {
    id: 3,
    module: "M2 · O LEAD NÃO PODE ESFRIAR",
    title: "Central de Leads",
    hook: '"Aqui é onde mais gasto e menos converto. Me ajuda?"',
    duration: "~5 min",
    steps: [
      {
        page: "mleads",
        target: null,
        pos: "center",
        title: "A tela mais importante pra você",
        body: "<p>Ana, é aqui que a operação ganha ou perde dinheiro. Lead de campanha é <strong>mídia paga esfriando em tempo real</strong>: cada minuto parado derruba a conversão. Sua missão é distribuir rápido.</p>",
      },
      {
        page: "mleads",
        target: "#page-mleads .kpi-grid",
        pos: "bottom",
        title: "Speed-to-lead — a sua régua",
        body: "<p>Os quatro números que importam: o <strong>lead mais antigo sem distribuir</strong> (vermelho se passou de 3 min), o <strong>tempo médio até distribuir</strong>, o <strong>% distribuído em menos de 3 min</strong> e o <strong>tempo médio até o 1º contato</strong>. O que não se mede, não se cobra.</p>",
      },
      {
        page: "mleads",
        target: "#page-mleads .table-pipe tbody tr",
        pos: "top",
        title: "O cronômetro de distribuição",
        body: "<p>Cada lead novo tem um <strong>contador correndo</strong>: verde no prazo, amarelo atenção, vermelho estourou (passou de 3 min). A fila vem <strong>ordenada por urgência</strong> — o mais antigo no topo — e os de campanha vêm marcados como prioridade.</p>",
        tip: {
          label: "Um clique",
          text: 'Quando um lead estoura, a linha fica vermelha e o botão "Distribuir" aparece em destaque. É só clicar.',
        },
      },
      {
        page: "mleads",
        target: "#page-mleads .row-actions",
        pos: "left",
        title: "O que você faz com cada lead",
        body: "<p>Na última coluna você comanda o lead, Ana: <strong>Distribuir</strong> (ou redistribuir, se já foi pra alguém), <strong>Puxar de volta</strong> pra fila, <strong>Bloquear</strong> um lead inválido, e abrir o <strong>histórico</strong> — que é a <strong>linha do tempo completa</strong> dele, com o tempo gasto em cada etapa e onde travou.</p>",
        tip: {
          label: "Distribuir com sugestão",
          text: "Ao clicar em Distribuir, o sistema já sugere a melhor franquia e o melhor vendedor por região e disponibilidade. Você confirma ou troca.",
        },
      },
      {
        page: "mleads",
        target: "#page-mleads .audit-note",
        pos: "bottom",
        title: "Manual cansa. Tem coisa melhor.",
        body: "<p>Distribuir na mão é o gargalo da operação. Por isso esse aviso te oferece o <strong>modo automático</strong> — e é pra lá que vamos agora.</p>",
      },
    ],
    outro: {
      hook: '"Esse é o pulo do gato da operação. Te mostro como deixar no automático."',
    },
  },
  {
    id: 4,
    module: "M2 · O LEAD NÃO PODE ESFRIAR",
    title: "Distribuição automática",
    hook: '"Dá pra parar de distribuir na mão?"',
    duration: "~3 min",
    steps: [
      {
        page: "mdist",
        target: "#mTriagemCard",
        pos: "bottom",
        title: "Leads devolvidos — sua triagem",
        body: '<p>Quando um vendedor não fecha, ele devolve o lead pra cá com um <strong>motivo</strong> (ex.: "Concorrência → fechou com outro corretor"). Aqui você faz a triagem: <strong>Remalho</strong> (volta pra fila de redistribuição) ou <strong>Descarte</strong> (encerra).</p><p>O sistema já <strong>sugere</strong> o destino pelo sub-motivo — você confirma ou muda. É você, na Matriz, quem decide.</p>',
        tip: {
          label: "Vira regra",
          text: 'Esses motivos podem virar regra de distribuição — ex.: "renovação distante" entra na fila de renovação automaticamente; "lead duplicado" é descartado na origem.',
        },
      },
      {
        page: "mdist",
        target: "#page-mdist .card-yellow",
        pos: "bottom",
        title: "O interruptor que muda o jogo",
        body: "<p>Aqui você liga a <strong>distribuição automática</strong>. No manual, o tempo médio até distribuir é de 2 minutos; no automático, cai pra <strong>~8 segundos</strong>. A Matriz passa a só tratar exceções.</p><p>É a maior alavanca de conversão que você tem, Ana.</p>",
        tip: {
          label: "Recomendado",
          text: "Numa operação que tem o lead como maior custo, o automático deveria ser o padrão. O manual fica só como exceção.",
        },
      },
      {
        page: "mdist",
        target: "#page-mdist .mode-grid",
        pos: "top",
        title: "A regra do automático",
        body: "<p>Você escolhe como o sistema distribui: por <strong>região</strong>, por <strong>performance</strong> (quem converte mais) ou por <strong>fila equilibrada</strong> (rodízio justo).</p>",
      },
      {
        page: "mdist",
        target: "#page-mdist .crit-list",
        pos: "right",
        title: "Os critérios da regra",
        body: "<p>Aqui você afina a automação, Ana: casar <strong>cidade/UF</strong>, respeitar a <strong>franquia responsável</strong>, só enviar pra <strong>vendedor disponível</strong>, favorecer quem tem melhor <strong>conversão</strong>, equilibrar o <strong>volume</strong> já recebido e respeitar o <strong>horário de atendimento</strong>. Liga ou desliga cada um.</p>",
        tip: {
          label: "SLA de reação",
          text: "No card ao lado você define quanto tempo o vendedor tem pra reagir (3, 5 ou 10 min) antes do lead voltar pra fila.",
        },
      },
      {
        page: "mdist",
        target: "#simResult",
        pos: "top",
        title: "Simule antes de confirmar",
        body: "<p>Antes de valer pra valer, rode a <strong>simulação</strong>: o sistema mostra, lead a lead da fila atual, pra quem cada um iria com a regra escolhida. Você confere e só então confirma. Nada muda sem você ver o resultado primeiro.</p>",
      },
    ],
    outro: {
      hook: '"Com o automático ligado, sobra tempo pra você fazer o que importa: acompanhar e melhorar."',
    },
  },
  {
    id: 5,
    module: "M3 · ACOMPANHAR, COBRAR, MELHORAR",
    title: "Franquias e Vendedores",
    hook: '"Como sei quem vai bem e quem travou?"',
    duration: "~3 min",
    steps: [
      {
        page: "mfranq",
        target: "#page-mfranq .mtable",
        pos: "top",
        title: "Cada franquia, lado a lado",
        body: "<p>Esta visão substitui a planilha de comparativo de franquias: leads, vendas, faturamento, comissão, estornos, conversão e meta de cada unidade. E clicando numa linha você abre o detalhe — é o próximo passo.</p>",
      },
      {
        page: "mfranq",
        target: "#page-mfranq .funnel",
        pos: "top",
        title: "Por dentro de uma franquia",
        body: "<p>Aqui está o raio-x da unidade: o <strong>funil da franquia</strong> (onde os leads caem), a <strong>equipe</strong> com cada vendedor, a <strong>meta do mês</strong> e as <strong>pendências financeiras</strong>. Esta é a Supper Rio Sul, que está abaixo da meta — e dá pra ver exatamente por quê.</p>",
      },
      {
        page: "mvend",
        target: "#page-mvend .mtable",
        pos: "top",
        title: "Cada vendedor, individualmente",
        body: "<p>Quem está vendendo, quem travou e quem precisa de apoio. Volume, tempo de 1º contato, cotações, propostas, vendas, conversão e comissão. O vendedor travado aparece sinalizado em vermelho.</p>",
      },
      {
        page: "mvend",
        target: "#page-mvend .funnel",
        pos: "top",
        title: "Por dentro de um vendedor",
        body: "<p>No detalhe você vê o <strong>funil individual</strong>, a <strong>performance por seguradora</strong>, comissão, premiação e cancelamentos. Esta é a Larissa, marcada como <strong>travada</strong>: conversão baixa e 1º contato lento. O sistema sugere até a ação — revisar a carga de leads e dar apoio comercial.</p>",
      },
    ],
    outro: {
      hook: '"Você viu o QUEM. Agora o ONDE: onde a operação perde tempo e lead."',
    },
  },
  {
    id: 6,
    module: "M3 · ACOMPANHAR, COBRAR, MELHORAR",
    title: "Supervisão — caça-gargalos",
    hook: '"Vejo que algo vai mal, mas não sei onde."',
    duration: "~4 min",
    steps: [
      {
        page: "msuperv",
        target: "#page-msuperv .gargalo-row",
        pos: "bottom",
        title: "Onde a operação trava",
        body: "<p>Para cada etapa da jornada do lead, o sistema mostra a <strong>conversão</strong> e o <strong>tempo médio</strong> gasto. A etapa em vermelho é o <strong>maior gargalo</strong> — onde mais se perde venda. Em 3 segundos você sabe onde focar treinamento e cobrança.</p>",
      },
      {
        page: "msuperv",
        target: "#page-msuperv .cmp-table",
        pos: "top",
        title: "Comparativo de vendedores",
        body: "<p>Os mesmos indicadores, vendedor a vendedor, com o <strong>ponto fraco de cada um destacado</strong>. É a sua central de supervisão — saber em quem agir e em quê.</p>",
        tip: {
          label: "Linha do tempo do lead",
          text: "Na Central de Leads, o ícone de histórico de qualquer lead abre a linha do tempo dele — com o tempo em cada etapa e o gargalo daquele caso específico.",
        },
      },
      {
        page: "mpipe",
        target: "#page-mpipe .kanban",
        pos: "top",
        title: "Pipeline geral da operação",
        body: "<p>O funil de toda a operação num só lugar, por etapa — com filtros por franquia, vendedor e seguradora. É a visão consolidada de onde estão os leads e onde a venda emperra.</p>",
      },
    ],
    outro: {
      hook: '"Achou o gargalo, agiu no vendedor certo. Falta acompanhar a venda até o dinheiro entrar."',
    },
  },
  {
    id: 7,
    module: "M3 · ACOMPANHAR, COBRAR, MELHORAR",
    title: "Controle de Vendas e transmissão",
    hook: '"Como acompanho a venda até a baixa?"',
    duration: "~4 min",
    steps: [
      {
        page: "mvendas",
        target: "#page-mvendas .toggle",
        pos: "bottom",
        title: "O extrato geral da operação",
        body: "<p>Aqui está toda a operação, em abas: <strong>Transmissão, Emitidas, Pagas, Não pagas e Canceladas</strong>. É o que unifica as planilhas de vendas e pagamentos num lugar só.</p>",
        prepare: "vendas-transmissao",
      },
      {
        page: "mvendas",
        target: "#page-mvendas .table-pipe",
        pos: "top",
        title: "A fase de transmissão",
        body: '<p>Antes da emissão existe a <strong>transmissão</strong>: a proposta já foi enviada e a seguradora está analisando. Se ela devolve uma <strong>pendência</strong>, aparece aqui — e a Matriz pode resolver as mais complexas direto, com o botão "Resolver".</p>',
        tip: {
          label: "Onde isso nasce",
          text: "A pendência aparece primeiro pro vendedor, na tela de Aceite & transmissão. Aqui você tem a visão geral e cobra o que travou.",
        },
      },
      {
        page: "mvendas",
        target: "#page-mvendas .table-pipe",
        pos: "top",
        title: "Emitidas, pagas, não pagas, canceladas",
        body: "<p>Passada a transmissão, as outras abas mostram a vida financeira da venda: <strong>Emitidas</strong>, <strong>Pagas</strong>, <strong>Não pagas</strong> (que você cobra) e <strong>Canceladas</strong>. Cada linha traz apólice, segurado, valor, comissão, vendedor, franquia e as datas de emissão e baixa. É o que unifica as planilhas de vendas e pagamentos.</p>",
        prepare: "vendas-nao-pagas",
      },
    ],
    outro: {
      hook: '"Acompanhou a venda. Última parada: remunerar e padronizar."',
    },
  },
  {
    id: 8,
    module: "M4 · REMUNERAR E PADRONIZAR",
    title: "Comissão, renovação e comunicação",
    hook: '"E a parte que gera conflito — a comissão?"',
    duration: "~4 min",
    steps: [
      {
        page: "mcomm",
        target: "#page-mcomm .audit-note",
        pos: "bottom",
        title: "Comissão com trava de auditoria",
        body: "<p>Comissão gera conflito, então aqui tem <strong>trava de auditoria</strong>: toda alteração fica registrada com autor, data e valor anterior. Nada muda sem rastro.</p>",
      },
      {
        page: "mcomm",
        target: "#page-mcomm .funnel",
        pos: "top",
        title: "Comissão por franquia e seguradora",
        body: "<p>O sistema abre a comissão por <strong>franquia</strong>, por <strong>vendedor</strong> e por <strong>seguradora</strong> — exatamente o que hoje vive em planilhas separadas. Você vê de onde vem cada real e fecha o mês com um clique.</p>",
      },
      {
        page: "mcomm",
        target: "#page-mcomm .actions-list",
        pos: "left",
        title: "Histórico de alterações",
        body: "<p>Toda mexida em comissão aparece aqui: <strong>quem</strong> alterou, <strong>quando</strong> e <strong>de quanto pra quanto</strong>. E o sistema detecta sozinho as <strong>divergências</strong> (ex.: comissão acima do teto da campanha) e sinaliza. É a sua proteção contra conflito.</p>",
      },
      {
        page: "mren",
        target: "#page-mren .audit-note",
        pos: "bottom",
        title: "Renovação no automático",
        body: '<p>Algo que a Supper não tinha estruturado: 60 dias antes do vencimento, o sistema cria sozinho um lead de <strong>"Renovação"</strong> no pipeline do vendedor. Carteira que se renova sozinha vira receita recorrente.</p>',
      },
      {
        page: "mmsgs",
        target: "#page-mmsgs .summary-chips",
        pos: "bottom",
        title: "Você cuida da comunicação",
        body: "<p>As <strong>mensagens prontas</strong> que o vendedor usa com o cliente são curadas aqui. Você inclui, edita e marca as <strong>oficiais</strong> — padronizando a comunicação da marca e evitando promessas indevidas de cobertura.</p>",
        tip: {
          label: "E tem mais",
          text: "Relatórios, Premiações, Estornos e Configurações completam a operação, no mesmo padrão visual — explore quando quiser.",
        },
      },
    ],
    outro: {
      hook: '"Quase lá, Ana. Ainda faltam as campanhas, os estornos e os relatórios pra você dominar."',
    },
  },
  {
    id: 9,
    module: "M4 · REMUNERAR E PADRONIZAR",
    title: "Premiações, estornos, relatórios e ajustes",
    hook: '"E o resto — campanhas, estornos, relatórios e regras?"',
    duration: "~4 min",
    steps: [
      {
        page: "mprem",
        target: "#page-mprem .mkpi-grid",
        pos: "top",
        title: "Premiações",
        body: "<p>As campanhas de incentivo e quanto cada vendedor já ganhou — total, pago e a pagar, por campanha. É como você acompanha e fecha a premiação do mês.</p>",
      },
      {
        page: "mestorno",
        target: "#page-mestorno .mkpi-grid",
        pos: "top",
        title: "Estornos e cancelamentos",
        body: "<p>Vendas canceladas no prazo de estorno e o <strong>impacto na comissão</strong>. Você vê motivo, vendedor e valor revertido — e age rápido quando a taxa de cancelamento sobe.</p>",
      },
      {
        page: "mrel",
        target: "#page-mrel .rep-grid",
        pos: "top",
        title: "Relatórios",
        body: "<p>A central de exportação: escolha o recorte (período, franquia, vendedor, seguradora) e baixe em <strong>PDF ou Excel</strong> — vendas, comissões, performance. O que vivia em planilhas, num clique.</p>",
      },
      {
        page: "mconf",
        target: "#page-mconf .card",
        pos: "top",
        title: "Configurações da operação",
        body: "<p>As regras gerais: metas, distribuição de leads, perfis e usuários, integrações (Quiver, seguradoras) e notificações. É onde você define como a operação funciona.</p>",
      },
    ],
    outro: {
      hook: '"Operação remunerada e padronizada. Falta a última peça: quem entra no sistema e com quais regras."',
    },
  },
  {
    id: 10,
    module: "M5 · ACESSOS E PERMISSÕES",
    title: "Acessos e permissões",
    hook: '"E quem decide quem entra e com quais regras?"',
    duration: "~4 min",
    steps: [
      {
        page: "macessos",
        target: null,
        pos: "center",
        hook: '"Essa é a porta de entrada do sistema — e a chave é sua."',
        title: "Acessos e permissões — a governança",
        body: "<p>Aqui é onde a Matriz <strong>autoriza quem entra</strong> e define <strong>com quais regras</strong> cada pessoa opera. Nenhum vendedor, franqueado ou master tem acesso antes de passar por esta tela.</p>",
        prepare: "acessos-pendentes",
      },
      {
        page: "macessos",
        target: "#page-macessos .table-pipe",
        pos: "top",
        title: "Pendentes de aprovação",
        body: '<p>Todo novo cadastro cai aqui — <strong>Pessoa Jurídica (CNPJ)</strong> ou <strong>Física (CPF)</strong>. Quando um <strong>Master franqueado</strong> cadastra um vendedor, ele chega com o selo <strong>"via Master"</strong>. Você vê o solicitante, o documento, o contato e quando enviou.</p>',
        prepare: "acessos-pendentes",
      },
      {
        page: "macessos",
        target: "#page-macessos .btn-yellow",
        pos: "left",
        title: "Analisar e classificar",
        body: "<p>No <strong>Analisar</strong>, você abre o <em>Formulário completo</em> do cadastro, escolhe o <strong>modelo</strong> e os parâmetros já vêm preenchidos — comissão, taxas, faixa de leads — que você pode <strong>ajustar caso a caso</strong>. Ao <strong>Liberar acesso</strong>, a pessoa recebe o e-mail de confirmação e entra no sistema.</p>",
        tip: {
          label: "Pessoa Física",
          text: "Se o cadastro é CPF (vendedor CLT), o sistema esconde o modelo de franquia e mostra os campos do CLT (equipe, faixa de leads) — porque a remuneração segue outra lógica.",
        },
        prepare: "acessos-pendentes",
      },
      {
        page: "macessos",
        target: "#page-macessos .card",
        pos: "top",
        title: "Desligamentos",
        body: "<p>Quando um <strong>master desliga um vendedor</strong>, o registro cai aqui — com quem foi desligado, de qual franquia, por quem e quando. É como a Matriz fica ciente de cada saída.</p><p>A regra é firme: um vendedor desligado <strong>só volta à base com aprovação da Matriz</strong> — pedidos de reinclusão chegam em <strong>Pendentes</strong> com o selo <strong>Reinclusão</strong>, e o master não consegue reincluir sozinho.</p>",
        prepare: "acessos-desligamentos",
      },
      {
        page: "macessos",
        target: "#page-macessos .toggle-sub",
        pos: "bottom",
        title: "Personalização geral — Modelo Franquia",
        body: "<p>Aqui ficam as <strong>regras padrão</strong> que alimentam a classificação. São <strong>6 modelos</strong>: os 5 <strong>Individuais</strong> (Smart, Conecta, Light, Link, Flex) — em que o franqueado opera como um vendedor — e o <strong>Full</strong>, com equipe abaixo. Cada um traz leads/dia, comissão de venda e renovação, taxas e royalties.</p><p>Logo abaixo está a <strong>Política de desconto (alçada)</strong>: o % máximo que cada modelo concede por seguradora antes de o pedido subir para o superior. Master e Supervisor têm a sua própria alçada nas abas correspondentes.</p>",
        prepare: "acessos-modelos-franquia",
      },
      {
        page: "macessos",
        target: "#page-macessos .card",
        pos: "top",
        title: "Personalização geral — Modelo Master",
        body: "<p>No <strong>Modelo Master</strong> ficam as regras padrão de comissionamento do Master sobre a equipe: percentual sobre a comissão do grupo, royalties + FPP, base de cálculo e pagamento — além da <strong>Campanha Elite Master</strong>, bônus trimestral por faixa de faturamento da equipe de franqueados.</p>",
        tip: {
          label: "Tudo num lugar",
          text: "O que hoje vive em PDFs e planilhas de comissão vira parâmetro editável — e alimenta automaticamente a classificação de cada acesso.",
        },
        prepare: "acessos-modelos-master",
      },
    ],
    outro: {
      hook: '"Pronto, Ana — agora você comanda a operação inteira e ainda controla quem entra nela. Conte comigo sempre que precisar."',
      big: true,
      final: true,
    },
  },
] satisfies TutorialSourceChapter[];
