/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthPendenteRouteImport } from './routes/auth.pendente'
import { Route as AuthCadastroRouteImport } from './routes/auth.cadastro'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedVendaPropostasRouteImport } from './routes/_authenticated/venda/propostas'
import { Route as AuthenticatedVendaPipelineRouteImport } from './routes/_authenticated/venda/pipeline'
import { Route as AuthenticatedVendaNovoLeadRouteImport } from './routes/_authenticated/venda/novo-lead'
import { Route as AuthenticatedVendaMensagensProntasRouteImport } from './routes/_authenticated/venda/mensagens-prontas'
import { Route as AuthenticatedVendaExtratoRouteImport } from './routes/_authenticated/venda/extrato'
import { Route as AuthenticatedVendaAtenderRouteImport } from './routes/_authenticated/venda/atender'
import { Route as AuthenticatedVendaAceiteRouteImport } from './routes/_authenticated/venda/aceite'
import { Route as AuthenticatedOperacaoVendasRouteImport } from './routes/_authenticated/operacao/vendas'
import { Route as AuthenticatedOperacaoSupervisaoRouteImport } from './routes/_authenticated/operacao/supervisao'
import { Route as AuthenticatedOperacaoRenovacoesRouteImport } from './routes/_authenticated/operacao/renovacoes'
import { Route as AuthenticatedOperacaoRelatoriosRouteImport } from './routes/_authenticated/operacao/relatorios'
import { Route as AuthenticatedOperacaoPremiacoesRouteImport } from './routes/_authenticated/operacao/premiacoes'
import { Route as AuthenticatedOperacaoPipelineGeralRouteImport } from './routes/_authenticated/operacao/pipeline-geral'
import { Route as AuthenticatedOperacaoPerdasRouteImport } from './routes/_authenticated/operacao/perdas'
import { Route as AuthenticatedOperacaoMensagensRouteImport } from './routes/_authenticated/operacao/mensagens'
import { Route as AuthenticatedOperacaoEstornosRouteImport } from './routes/_authenticated/operacao/estornos'
import { Route as AuthenticatedOperacaoConfiguracoesRouteImport } from './routes/_authenticated/operacao/configuracoes'
import { Route as AuthenticatedOperacaoComissoesRouteImport } from './routes/_authenticated/operacao/comissoes'
import { Route as AuthenticatedOperacaoAprovacoesRouteImport } from './routes/_authenticated/operacao/aprovacoes'
import { Route as AuthenticatedOperacaoAcessosRouteImport } from './routes/_authenticated/operacao/acessos'
import { Route as AuthenticatedComandoVisaoGeralRouteImport } from './routes/_authenticated/comando/visao-geral'
import { Route as AuthenticatedComandoLeadsRouteImport } from './routes/_authenticated/comando/leads'
import { Route as AuthenticatedComandoDistribuicaoRouteImport } from './routes/_authenticated/comando/distribuicao'
import { Route as AuthenticatedVendaCotacoesIndexRouteImport } from './routes/_authenticated/venda/cotacoes.index'
import { Route as AuthenticatedOperacaoVendedoresIndexRouteImport } from './routes/_authenticated/operacao/vendedores.index'
import { Route as AuthenticatedOperacaoFranquiasIndexRouteImport } from './routes/_authenticated/operacao/franquias.index'
import { Route as AuthenticatedVendaCotacoesIdRouteImport } from './routes/_authenticated/venda/cotacoes.$id'
import { Route as AuthenticatedOperacaoVendedoresIdRouteImport } from './routes/_authenticated/operacao/vendedores.$id'
import { Route as AuthenticatedOperacaoFranquiasIdRouteImport } from './routes/_authenticated/operacao/franquias.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPendenteRoute = AuthPendenteRouteImport.update({
  id: '/auth/pendente',
  path: '/auth/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCadastroRoute = AuthCadastroRouteImport.update({
  id: '/auth/cadastro',
  path: '/auth/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendaPropostasRoute =
  AuthenticatedVendaPropostasRouteImport.update({
    id: '/venda/propostas',
    path: '/venda/propostas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendaPipelineRoute =
  AuthenticatedVendaPipelineRouteImport.update({
    id: '/venda/pipeline',
    path: '/venda/pipeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendaNovoLeadRoute =
  AuthenticatedVendaNovoLeadRouteImport.update({
    id: '/venda/novo-lead',
    path: '/venda/novo-lead',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendaMensagensProntasRoute =
  AuthenticatedVendaMensagensProntasRouteImport.update({
    id: '/venda/mensagens-prontas',
    path: '/venda/mensagens-prontas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendaExtratoRoute =
  AuthenticatedVendaExtratoRouteImport.update({
    id: '/venda/extrato',
    path: '/venda/extrato',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendaAtenderRoute =
  AuthenticatedVendaAtenderRouteImport.update({
    id: '/venda/atender',
    path: '/venda/atender',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendaAceiteRoute =
  AuthenticatedVendaAceiteRouteImport.update({
    id: '/venda/aceite',
    path: '/venda/aceite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoVendasRoute =
  AuthenticatedOperacaoVendasRouteImport.update({
    id: '/operacao/vendas',
    path: '/operacao/vendas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoSupervisaoRoute =
  AuthenticatedOperacaoSupervisaoRouteImport.update({
    id: '/operacao/supervisao',
    path: '/operacao/supervisao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoRenovacoesRoute =
  AuthenticatedOperacaoRenovacoesRouteImport.update({
    id: '/operacao/renovacoes',
    path: '/operacao/renovacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoRelatoriosRoute =
  AuthenticatedOperacaoRelatoriosRouteImport.update({
    id: '/operacao/relatorios',
    path: '/operacao/relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoPremiacoesRoute =
  AuthenticatedOperacaoPremiacoesRouteImport.update({
    id: '/operacao/premiacoes',
    path: '/operacao/premiacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoPipelineGeralRoute =
  AuthenticatedOperacaoPipelineGeralRouteImport.update({
    id: '/operacao/pipeline-geral',
    path: '/operacao/pipeline-geral',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoPerdasRoute =
  AuthenticatedOperacaoPerdasRouteImport.update({
    id: '/operacao/perdas',
    path: '/operacao/perdas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoMensagensRoute =
  AuthenticatedOperacaoMensagensRouteImport.update({
    id: '/operacao/mensagens',
    path: '/operacao/mensagens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoEstornosRoute =
  AuthenticatedOperacaoEstornosRouteImport.update({
    id: '/operacao/estornos',
    path: '/operacao/estornos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoConfiguracoesRoute =
  AuthenticatedOperacaoConfiguracoesRouteImport.update({
    id: '/operacao/configuracoes',
    path: '/operacao/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoComissoesRoute =
  AuthenticatedOperacaoComissoesRouteImport.update({
    id: '/operacao/comissoes',
    path: '/operacao/comissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoAprovacoesRoute =
  AuthenticatedOperacaoAprovacoesRouteImport.update({
    id: '/operacao/aprovacoes',
    path: '/operacao/aprovacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoAcessosRoute =
  AuthenticatedOperacaoAcessosRouteImport.update({
    id: '/operacao/acessos',
    path: '/operacao/acessos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComandoVisaoGeralRoute =
  AuthenticatedComandoVisaoGeralRouteImport.update({
    id: '/comando/visao-geral',
    path: '/comando/visao-geral',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComandoLeadsRoute =
  AuthenticatedComandoLeadsRouteImport.update({
    id: '/comando/leads',
    path: '/comando/leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComandoDistribuicaoRoute =
  AuthenticatedComandoDistribuicaoRouteImport.update({
    id: '/comando/distribuicao',
    path: '/comando/distribuicao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendaCotacoesIndexRoute =
  AuthenticatedVendaCotacoesIndexRouteImport.update({
    id: '/venda/cotacoes/',
    path: '/venda/cotacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoVendedoresIndexRoute =
  AuthenticatedOperacaoVendedoresIndexRouteImport.update({
    id: '/operacao/vendedores/',
    path: '/operacao/vendedores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoFranquiasIndexRoute =
  AuthenticatedOperacaoFranquiasIndexRouteImport.update({
    id: '/operacao/franquias/',
    path: '/operacao/franquias/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendaCotacoesIdRoute =
  AuthenticatedVendaCotacoesIdRouteImport.update({
    id: '/venda/cotacoes/$id',
    path: '/venda/cotacoes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoVendedoresIdRoute =
  AuthenticatedOperacaoVendedoresIdRouteImport.update({
    id: '/operacao/vendedores/$id',
    path: '/operacao/vendedores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoFranquiasIdRoute =
  AuthenticatedOperacaoFranquiasIdRouteImport.update({
    id: '/operacao/franquias/$id',
    path: '/operacao/franquias/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/pendente': typeof AuthPendenteRoute
  '/auth/': typeof AuthIndexRoute
  '/comando/distribuicao': typeof AuthenticatedComandoDistribuicaoRoute
  '/comando/leads': typeof AuthenticatedComandoLeadsRoute
  '/comando/visao-geral': typeof AuthenticatedComandoVisaoGeralRoute
  '/operacao/acessos': typeof AuthenticatedOperacaoAcessosRoute
  '/operacao/aprovacoes': typeof AuthenticatedOperacaoAprovacoesRoute
  '/operacao/comissoes': typeof AuthenticatedOperacaoComissoesRoute
  '/operacao/configuracoes': typeof AuthenticatedOperacaoConfiguracoesRoute
  '/operacao/estornos': typeof AuthenticatedOperacaoEstornosRoute
  '/operacao/mensagens': typeof AuthenticatedOperacaoMensagensRoute
  '/operacao/perdas': typeof AuthenticatedOperacaoPerdasRoute
  '/operacao/pipeline-geral': typeof AuthenticatedOperacaoPipelineGeralRoute
  '/operacao/premiacoes': typeof AuthenticatedOperacaoPremiacoesRoute
  '/operacao/relatorios': typeof AuthenticatedOperacaoRelatoriosRoute
  '/operacao/renovacoes': typeof AuthenticatedOperacaoRenovacoesRoute
  '/operacao/supervisao': typeof AuthenticatedOperacaoSupervisaoRoute
  '/operacao/vendas': typeof AuthenticatedOperacaoVendasRoute
  '/venda/aceite': typeof AuthenticatedVendaAceiteRoute
  '/venda/atender': typeof AuthenticatedVendaAtenderRoute
  '/venda/extrato': typeof AuthenticatedVendaExtratoRoute
  '/venda/mensagens-prontas': typeof AuthenticatedVendaMensagensProntasRoute
  '/venda/novo-lead': typeof AuthenticatedVendaNovoLeadRoute
  '/venda/pipeline': typeof AuthenticatedVendaPipelineRoute
  '/venda/propostas': typeof AuthenticatedVendaPropostasRoute
  '/operacao/franquias/$id': typeof AuthenticatedOperacaoFranquiasIdRoute
  '/operacao/vendedores/$id': typeof AuthenticatedOperacaoVendedoresIdRoute
  '/venda/cotacoes/$id': typeof AuthenticatedVendaCotacoesIdRoute
  '/operacao/franquias/': typeof AuthenticatedOperacaoFranquiasIndexRoute
  '/operacao/vendedores/': typeof AuthenticatedOperacaoVendedoresIndexRoute
  '/venda/cotacoes/': typeof AuthenticatedVendaCotacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/pendente': typeof AuthPendenteRoute
  '/auth': typeof AuthIndexRoute
  '/comando/distribuicao': typeof AuthenticatedComandoDistribuicaoRoute
  '/comando/leads': typeof AuthenticatedComandoLeadsRoute
  '/comando/visao-geral': typeof AuthenticatedComandoVisaoGeralRoute
  '/operacao/acessos': typeof AuthenticatedOperacaoAcessosRoute
  '/operacao/aprovacoes': typeof AuthenticatedOperacaoAprovacoesRoute
  '/operacao/comissoes': typeof AuthenticatedOperacaoComissoesRoute
  '/operacao/configuracoes': typeof AuthenticatedOperacaoConfiguracoesRoute
  '/operacao/estornos': typeof AuthenticatedOperacaoEstornosRoute
  '/operacao/mensagens': typeof AuthenticatedOperacaoMensagensRoute
  '/operacao/perdas': typeof AuthenticatedOperacaoPerdasRoute
  '/operacao/pipeline-geral': typeof AuthenticatedOperacaoPipelineGeralRoute
  '/operacao/premiacoes': typeof AuthenticatedOperacaoPremiacoesRoute
  '/operacao/relatorios': typeof AuthenticatedOperacaoRelatoriosRoute
  '/operacao/renovacoes': typeof AuthenticatedOperacaoRenovacoesRoute
  '/operacao/supervisao': typeof AuthenticatedOperacaoSupervisaoRoute
  '/operacao/vendas': typeof AuthenticatedOperacaoVendasRoute
  '/venda/aceite': typeof AuthenticatedVendaAceiteRoute
  '/venda/atender': typeof AuthenticatedVendaAtenderRoute
  '/venda/extrato': typeof AuthenticatedVendaExtratoRoute
  '/venda/mensagens-prontas': typeof AuthenticatedVendaMensagensProntasRoute
  '/venda/novo-lead': typeof AuthenticatedVendaNovoLeadRoute
  '/venda/pipeline': typeof AuthenticatedVendaPipelineRoute
  '/venda/propostas': typeof AuthenticatedVendaPropostasRoute
  '/operacao/franquias/$id': typeof AuthenticatedOperacaoFranquiasIdRoute
  '/operacao/vendedores/$id': typeof AuthenticatedOperacaoVendedoresIdRoute
  '/venda/cotacoes/$id': typeof AuthenticatedVendaCotacoesIdRoute
  '/operacao/franquias': typeof AuthenticatedOperacaoFranquiasIndexRoute
  '/operacao/vendedores': typeof AuthenticatedOperacaoVendedoresIndexRoute
  '/venda/cotacoes': typeof AuthenticatedVendaCotacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/pendente': typeof AuthPendenteRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/comando/distribuicao': typeof AuthenticatedComandoDistribuicaoRoute
  '/_authenticated/comando/leads': typeof AuthenticatedComandoLeadsRoute
  '/_authenticated/comando/visao-geral': typeof AuthenticatedComandoVisaoGeralRoute
  '/_authenticated/operacao/acessos': typeof AuthenticatedOperacaoAcessosRoute
  '/_authenticated/operacao/aprovacoes': typeof AuthenticatedOperacaoAprovacoesRoute
  '/_authenticated/operacao/comissoes': typeof AuthenticatedOperacaoComissoesRoute
  '/_authenticated/operacao/configuracoes': typeof AuthenticatedOperacaoConfiguracoesRoute
  '/_authenticated/operacao/estornos': typeof AuthenticatedOperacaoEstornosRoute
  '/_authenticated/operacao/mensagens': typeof AuthenticatedOperacaoMensagensRoute
  '/_authenticated/operacao/perdas': typeof AuthenticatedOperacaoPerdasRoute
  '/_authenticated/operacao/pipeline-geral': typeof AuthenticatedOperacaoPipelineGeralRoute
  '/_authenticated/operacao/premiacoes': typeof AuthenticatedOperacaoPremiacoesRoute
  '/_authenticated/operacao/relatorios': typeof AuthenticatedOperacaoRelatoriosRoute
  '/_authenticated/operacao/renovacoes': typeof AuthenticatedOperacaoRenovacoesRoute
  '/_authenticated/operacao/supervisao': typeof AuthenticatedOperacaoSupervisaoRoute
  '/_authenticated/operacao/vendas': typeof AuthenticatedOperacaoVendasRoute
  '/_authenticated/venda/aceite': typeof AuthenticatedVendaAceiteRoute
  '/_authenticated/venda/atender': typeof AuthenticatedVendaAtenderRoute
  '/_authenticated/venda/extrato': typeof AuthenticatedVendaExtratoRoute
  '/_authenticated/venda/mensagens-prontas': typeof AuthenticatedVendaMensagensProntasRoute
  '/_authenticated/venda/novo-lead': typeof AuthenticatedVendaNovoLeadRoute
  '/_authenticated/venda/pipeline': typeof AuthenticatedVendaPipelineRoute
  '/_authenticated/venda/propostas': typeof AuthenticatedVendaPropostasRoute
  '/_authenticated/operacao/franquias/$id': typeof AuthenticatedOperacaoFranquiasIdRoute
  '/_authenticated/operacao/vendedores/$id': typeof AuthenticatedOperacaoVendedoresIdRoute
  '/_authenticated/venda/cotacoes/$id': typeof AuthenticatedVendaCotacoesIdRoute
  '/_authenticated/operacao/franquias/': typeof AuthenticatedOperacaoFranquiasIndexRoute
  '/_authenticated/operacao/vendedores/': typeof AuthenticatedOperacaoVendedoresIndexRoute
  '/_authenticated/venda/cotacoes/': typeof AuthenticatedVendaCotacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inicio'
    | '/auth/cadastro'
    | '/auth/pendente'
    | '/auth/'
    | '/comando/distribuicao'
    | '/comando/leads'
    | '/comando/visao-geral'
    | '/operacao/acessos'
    | '/operacao/aprovacoes'
    | '/operacao/comissoes'
    | '/operacao/configuracoes'
    | '/operacao/estornos'
    | '/operacao/mensagens'
    | '/operacao/perdas'
    | '/operacao/pipeline-geral'
    | '/operacao/premiacoes'
    | '/operacao/relatorios'
    | '/operacao/renovacoes'
    | '/operacao/supervisao'
    | '/operacao/vendas'
    | '/venda/aceite'
    | '/venda/atender'
    | '/venda/extrato'
    | '/venda/mensagens-prontas'
    | '/venda/novo-lead'
    | '/venda/pipeline'
    | '/venda/propostas'
    | '/operacao/franquias/$id'
    | '/operacao/vendedores/$id'
    | '/venda/cotacoes/$id'
    | '/operacao/franquias/'
    | '/operacao/vendedores/'
    | '/venda/cotacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inicio'
    | '/auth/cadastro'
    | '/auth/pendente'
    | '/auth'
    | '/comando/distribuicao'
    | '/comando/leads'
    | '/comando/visao-geral'
    | '/operacao/acessos'
    | '/operacao/aprovacoes'
    | '/operacao/comissoes'
    | '/operacao/configuracoes'
    | '/operacao/estornos'
    | '/operacao/mensagens'
    | '/operacao/perdas'
    | '/operacao/pipeline-geral'
    | '/operacao/premiacoes'
    | '/operacao/relatorios'
    | '/operacao/renovacoes'
    | '/operacao/supervisao'
    | '/operacao/vendas'
    | '/venda/aceite'
    | '/venda/atender'
    | '/venda/extrato'
    | '/venda/mensagens-prontas'
    | '/venda/novo-lead'
    | '/venda/pipeline'
    | '/venda/propostas'
    | '/operacao/franquias/$id'
    | '/operacao/vendedores/$id'
    | '/venda/cotacoes/$id'
    | '/operacao/franquias'
    | '/operacao/vendedores'
    | '/venda/cotacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/inicio'
    | '/auth/cadastro'
    | '/auth/pendente'
    | '/auth/'
    | '/_authenticated/comando/distribuicao'
    | '/_authenticated/comando/leads'
    | '/_authenticated/comando/visao-geral'
    | '/_authenticated/operacao/acessos'
    | '/_authenticated/operacao/aprovacoes'
    | '/_authenticated/operacao/comissoes'
    | '/_authenticated/operacao/configuracoes'
    | '/_authenticated/operacao/estornos'
    | '/_authenticated/operacao/mensagens'
    | '/_authenticated/operacao/perdas'
    | '/_authenticated/operacao/pipeline-geral'
    | '/_authenticated/operacao/premiacoes'
    | '/_authenticated/operacao/relatorios'
    | '/_authenticated/operacao/renovacoes'
    | '/_authenticated/operacao/supervisao'
    | '/_authenticated/operacao/vendas'
    | '/_authenticated/venda/aceite'
    | '/_authenticated/venda/atender'
    | '/_authenticated/venda/extrato'
    | '/_authenticated/venda/mensagens-prontas'
    | '/_authenticated/venda/novo-lead'
    | '/_authenticated/venda/pipeline'
    | '/_authenticated/venda/propostas'
    | '/_authenticated/operacao/franquias/$id'
    | '/_authenticated/operacao/vendedores/$id'
    | '/_authenticated/venda/cotacoes/$id'
    | '/_authenticated/operacao/franquias/'
    | '/_authenticated/operacao/vendedores/'
    | '/_authenticated/venda/cotacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthCadastroRoute: typeof AuthCadastroRoute
  AuthPendenteRoute: typeof AuthPendenteRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/pendente': {
      id: '/auth/pendente'
      path: '/auth/pendente'
      fullPath: '/auth/pendente'
      preLoaderRoute: typeof AuthPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/cadastro': {
      id: '/auth/cadastro'
      path: '/auth/cadastro'
      fullPath: '/auth/cadastro'
      preLoaderRoute: typeof AuthCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/venda/propostas': {
      id: '/_authenticated/venda/propostas'
      path: '/venda/propostas'
      fullPath: '/venda/propostas'
      preLoaderRoute: typeof AuthenticatedVendaPropostasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/venda/pipeline': {
      id: '/_authenticated/venda/pipeline'
      path: '/venda/pipeline'
      fullPath: '/venda/pipeline'
      preLoaderRoute: typeof AuthenticatedVendaPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/venda/novo-lead': {
      id: '/_authenticated/venda/novo-lead'
      path: '/venda/novo-lead'
      fullPath: '/venda/novo-lead'
      preLoaderRoute: typeof AuthenticatedVendaNovoLeadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/venda/mensagens-prontas': {
      id: '/_authenticated/venda/mensagens-prontas'
      path: '/venda/mensagens-prontas'
      fullPath: '/venda/mensagens-prontas'
      preLoaderRoute: typeof AuthenticatedVendaMensagensProntasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/venda/extrato': {
      id: '/_authenticated/venda/extrato'
      path: '/venda/extrato'
      fullPath: '/venda/extrato'
      preLoaderRoute: typeof AuthenticatedVendaExtratoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/venda/atender': {
      id: '/_authenticated/venda/atender'
      path: '/venda/atender'
      fullPath: '/venda/atender'
      preLoaderRoute: typeof AuthenticatedVendaAtenderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/venda/aceite': {
      id: '/_authenticated/venda/aceite'
      path: '/venda/aceite'
      fullPath: '/venda/aceite'
      preLoaderRoute: typeof AuthenticatedVendaAceiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/vendas': {
      id: '/_authenticated/operacao/vendas'
      path: '/operacao/vendas'
      fullPath: '/operacao/vendas'
      preLoaderRoute: typeof AuthenticatedOperacaoVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/supervisao': {
      id: '/_authenticated/operacao/supervisao'
      path: '/operacao/supervisao'
      fullPath: '/operacao/supervisao'
      preLoaderRoute: typeof AuthenticatedOperacaoSupervisaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/renovacoes': {
      id: '/_authenticated/operacao/renovacoes'
      path: '/operacao/renovacoes'
      fullPath: '/operacao/renovacoes'
      preLoaderRoute: typeof AuthenticatedOperacaoRenovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/relatorios': {
      id: '/_authenticated/operacao/relatorios'
      path: '/operacao/relatorios'
      fullPath: '/operacao/relatorios'
      preLoaderRoute: typeof AuthenticatedOperacaoRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/premiacoes': {
      id: '/_authenticated/operacao/premiacoes'
      path: '/operacao/premiacoes'
      fullPath: '/operacao/premiacoes'
      preLoaderRoute: typeof AuthenticatedOperacaoPremiacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/pipeline-geral': {
      id: '/_authenticated/operacao/pipeline-geral'
      path: '/operacao/pipeline-geral'
      fullPath: '/operacao/pipeline-geral'
      preLoaderRoute: typeof AuthenticatedOperacaoPipelineGeralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/perdas': {
      id: '/_authenticated/operacao/perdas'
      path: '/operacao/perdas'
      fullPath: '/operacao/perdas'
      preLoaderRoute: typeof AuthenticatedOperacaoPerdasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/mensagens': {
      id: '/_authenticated/operacao/mensagens'
      path: '/operacao/mensagens'
      fullPath: '/operacao/mensagens'
      preLoaderRoute: typeof AuthenticatedOperacaoMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/estornos': {
      id: '/_authenticated/operacao/estornos'
      path: '/operacao/estornos'
      fullPath: '/operacao/estornos'
      preLoaderRoute: typeof AuthenticatedOperacaoEstornosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/configuracoes': {
      id: '/_authenticated/operacao/configuracoes'
      path: '/operacao/configuracoes'
      fullPath: '/operacao/configuracoes'
      preLoaderRoute: typeof AuthenticatedOperacaoConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/comissoes': {
      id: '/_authenticated/operacao/comissoes'
      path: '/operacao/comissoes'
      fullPath: '/operacao/comissoes'
      preLoaderRoute: typeof AuthenticatedOperacaoComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/aprovacoes': {
      id: '/_authenticated/operacao/aprovacoes'
      path: '/operacao/aprovacoes'
      fullPath: '/operacao/aprovacoes'
      preLoaderRoute: typeof AuthenticatedOperacaoAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/acessos': {
      id: '/_authenticated/operacao/acessos'
      path: '/operacao/acessos'
      fullPath: '/operacao/acessos'
      preLoaderRoute: typeof AuthenticatedOperacaoAcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comando/visao-geral': {
      id: '/_authenticated/comando/visao-geral'
      path: '/comando/visao-geral'
      fullPath: '/comando/visao-geral'
      preLoaderRoute: typeof AuthenticatedComandoVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comando/leads': {
      id: '/_authenticated/comando/leads'
      path: '/comando/leads'
      fullPath: '/comando/leads'
      preLoaderRoute: typeof AuthenticatedComandoLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comando/distribuicao': {
      id: '/_authenticated/comando/distribuicao'
      path: '/comando/distribuicao'
      fullPath: '/comando/distribuicao'
      preLoaderRoute: typeof AuthenticatedComandoDistribuicaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/venda/cotacoes/': {
      id: '/_authenticated/venda/cotacoes/'
      path: '/venda/cotacoes'
      fullPath: '/venda/cotacoes/'
      preLoaderRoute: typeof AuthenticatedVendaCotacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/vendedores/': {
      id: '/_authenticated/operacao/vendedores/'
      path: '/operacao/vendedores'
      fullPath: '/operacao/vendedores/'
      preLoaderRoute: typeof AuthenticatedOperacaoVendedoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/franquias/': {
      id: '/_authenticated/operacao/franquias/'
      path: '/operacao/franquias'
      fullPath: '/operacao/franquias/'
      preLoaderRoute: typeof AuthenticatedOperacaoFranquiasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/venda/cotacoes/$id': {
      id: '/_authenticated/venda/cotacoes/$id'
      path: '/venda/cotacoes/$id'
      fullPath: '/venda/cotacoes/$id'
      preLoaderRoute: typeof AuthenticatedVendaCotacoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/vendedores/$id': {
      id: '/_authenticated/operacao/vendedores/$id'
      path: '/operacao/vendedores/$id'
      fullPath: '/operacao/vendedores/$id'
      preLoaderRoute: typeof AuthenticatedOperacaoVendedoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/franquias/$id': {
      id: '/_authenticated/operacao/franquias/$id'
      path: '/operacao/franquias/$id'
      fullPath: '/operacao/franquias/$id'
      preLoaderRoute: typeof AuthenticatedOperacaoFranquiasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedComandoDistribuicaoRoute: typeof AuthenticatedComandoDistribuicaoRoute
  AuthenticatedComandoLeadsRoute: typeof AuthenticatedComandoLeadsRoute
  AuthenticatedComandoVisaoGeralRoute: typeof AuthenticatedComandoVisaoGeralRoute
  AuthenticatedOperacaoAcessosRoute: typeof AuthenticatedOperacaoAcessosRoute
  AuthenticatedOperacaoAprovacoesRoute: typeof AuthenticatedOperacaoAprovacoesRoute
  AuthenticatedOperacaoComissoesRoute: typeof AuthenticatedOperacaoComissoesRoute
  AuthenticatedOperacaoConfiguracoesRoute: typeof AuthenticatedOperacaoConfiguracoesRoute
  AuthenticatedOperacaoEstornosRoute: typeof AuthenticatedOperacaoEstornosRoute
  AuthenticatedOperacaoMensagensRoute: typeof AuthenticatedOperacaoMensagensRoute
  AuthenticatedOperacaoPerdasRoute: typeof AuthenticatedOperacaoPerdasRoute
  AuthenticatedOperacaoPipelineGeralRoute: typeof AuthenticatedOperacaoPipelineGeralRoute
  AuthenticatedOperacaoPremiacoesRoute: typeof AuthenticatedOperacaoPremiacoesRoute
  AuthenticatedOperacaoRelatoriosRoute: typeof AuthenticatedOperacaoRelatoriosRoute
  AuthenticatedOperacaoRenovacoesRoute: typeof AuthenticatedOperacaoRenovacoesRoute
  AuthenticatedOperacaoSupervisaoRoute: typeof AuthenticatedOperacaoSupervisaoRoute
  AuthenticatedOperacaoVendasRoute: typeof AuthenticatedOperacaoVendasRoute
  AuthenticatedVendaAceiteRoute: typeof AuthenticatedVendaAceiteRoute
  AuthenticatedVendaAtenderRoute: typeof AuthenticatedVendaAtenderRoute
  AuthenticatedVendaExtratoRoute: typeof AuthenticatedVendaExtratoRoute
  AuthenticatedVendaMensagensProntasRoute: typeof AuthenticatedVendaMensagensProntasRoute
  AuthenticatedVendaNovoLeadRoute: typeof AuthenticatedVendaNovoLeadRoute
  AuthenticatedVendaPipelineRoute: typeof AuthenticatedVendaPipelineRoute
  AuthenticatedVendaPropostasRoute: typeof AuthenticatedVendaPropostasRoute
  AuthenticatedOperacaoFranquiasIdRoute: typeof AuthenticatedOperacaoFranquiasIdRoute
  AuthenticatedOperacaoVendedoresIdRoute: typeof AuthenticatedOperacaoVendedoresIdRoute
  AuthenticatedVendaCotacoesIdRoute: typeof AuthenticatedVendaCotacoesIdRoute
  AuthenticatedOperacaoFranquiasIndexRoute: typeof AuthenticatedOperacaoFranquiasIndexRoute
  AuthenticatedOperacaoVendedoresIndexRoute: typeof AuthenticatedOperacaoVendedoresIndexRoute
  AuthenticatedVendaCotacoesIndexRoute: typeof AuthenticatedVendaCotacoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedComandoDistribuicaoRoute: AuthenticatedComandoDistribuicaoRoute,
  AuthenticatedComandoLeadsRoute: AuthenticatedComandoLeadsRoute,
  AuthenticatedComandoVisaoGeralRoute: AuthenticatedComandoVisaoGeralRoute,
  AuthenticatedOperacaoAcessosRoute: AuthenticatedOperacaoAcessosRoute,
  AuthenticatedOperacaoAprovacoesRoute: AuthenticatedOperacaoAprovacoesRoute,
  AuthenticatedOperacaoComissoesRoute: AuthenticatedOperacaoComissoesRoute,
  AuthenticatedOperacaoConfiguracoesRoute:
    AuthenticatedOperacaoConfiguracoesRoute,
  AuthenticatedOperacaoEstornosRoute: AuthenticatedOperacaoEstornosRoute,
  AuthenticatedOperacaoMensagensRoute: AuthenticatedOperacaoMensagensRoute,
  AuthenticatedOperacaoPerdasRoute: AuthenticatedOperacaoPerdasRoute,
  AuthenticatedOperacaoPipelineGeralRoute:
    AuthenticatedOperacaoPipelineGeralRoute,
  AuthenticatedOperacaoPremiacoesRoute: AuthenticatedOperacaoPremiacoesRoute,
  AuthenticatedOperacaoRelatoriosRoute: AuthenticatedOperacaoRelatoriosRoute,
  AuthenticatedOperacaoRenovacoesRoute: AuthenticatedOperacaoRenovacoesRoute,
  AuthenticatedOperacaoSupervisaoRoute: AuthenticatedOperacaoSupervisaoRoute,
  AuthenticatedOperacaoVendasRoute: AuthenticatedOperacaoVendasRoute,
  AuthenticatedVendaAceiteRoute: AuthenticatedVendaAceiteRoute,
  AuthenticatedVendaAtenderRoute: AuthenticatedVendaAtenderRoute,
  AuthenticatedVendaExtratoRoute: AuthenticatedVendaExtratoRoute,
  AuthenticatedVendaMensagensProntasRoute:
    AuthenticatedVendaMensagensProntasRoute,
  AuthenticatedVendaNovoLeadRoute: AuthenticatedVendaNovoLeadRoute,
  AuthenticatedVendaPipelineRoute: AuthenticatedVendaPipelineRoute,
  AuthenticatedVendaPropostasRoute: AuthenticatedVendaPropostasRoute,
  AuthenticatedOperacaoFranquiasIdRoute: AuthenticatedOperacaoFranquiasIdRoute,
  AuthenticatedOperacaoVendedoresIdRoute:
    AuthenticatedOperacaoVendedoresIdRoute,
  AuthenticatedVendaCotacoesIdRoute: AuthenticatedVendaCotacoesIdRoute,
  AuthenticatedOperacaoFranquiasIndexRoute:
    AuthenticatedOperacaoFranquiasIndexRoute,
  AuthenticatedOperacaoVendedoresIndexRoute:
    AuthenticatedOperacaoVendedoresIndexRoute,
  AuthenticatedVendaCotacoesIndexRoute: AuthenticatedVendaCotacoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthCadastroRoute: AuthCadastroRoute,
  AuthPendenteRoute: AuthPendenteRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
